name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Update Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
    
    - name: Build
      run: cargo build --manifest-path bot48/Cargo.toml --release
    
    - uses: actions/upload-artifact@v2
      with:
        name: bot48
        path: bot48/target/release/bot48
    #- name: Run tests
    #  run: cargo test --verbose
