name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      working-directory: ./bot48
      run: cargo build --release
    
    - uses: actions/upload-artifact@v2
      with:
        name: bot48
        path: bot48/target/release/bot48
    #- name: Run tests
    #  run: cargo test --verbose
